version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.4

    working_directory: ~/tmp

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules/
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: npm test


