version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.4

    working_directory: ~/tmp

    steps:
      - checkout
      - restore_cache:
          keys:
            - v0.2-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v0.2-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test


